Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [2]:
# Ковариация по формуле
np.mean(zp*ks)-np.mean(zp)*np.mean(ks)

9157.839999999997

In [3]:
## Проверка
np.cov(zp,ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Коэф-т корреляции Пирсона находится по формуле:

$$r_{XY} = \frac{cov_{XY}}{\sigma_{X}\sigma_{Y}}$$

Ковариация уже известна. Осталось найти $\sigma$

In [4]:
# Сигма_х
print (np.std(zp, ddof=0))
print (np.std(zp, ddof=1))

59.115480206118605
62.31318747531162


In [5]:
# Сигма_y
print (np.std(ks, ddof=0))
print (np.std(ks, ddof=1))

174.55340157098058
183.99544076477068


In [6]:
## первый ваариант. 
np.cov(zp,ks, ddof=0)/(np.std(zp)*np.std(ks))

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [7]:
## второй вариант
np.cov(zp,ks, ddof=1)/(np.std(zp, ddof=1)*np.std(ks, ddof=1))

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [8]:
## Проверка.
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

Решение:

Формула нахождения довертельного интервала ($\sigma$ не известна):

$$ \overline x \pm (t_{a/2}\cdot \frac{\sigma}{\sqrt n})$$


α=5% . т.к. у нас не односторонний критерий, то для вычеслений используем 2.5%.
При α=0,025 и при v=9 $t$ табличное = 2.262. Найдем интервал:

$$ 118.1 \pm (2.262 \cdot \frac{10.55}{\sqrt {10}})$$

т.е. мат ожидание находится в интервале [110.56;125.64] с вероятностью 95%

$$ 118.1 \pm (2.262 \cdot \frac{10.55}{\sqrt {10}})$$

In [9]:
from math import sqrt
iq=[131, 125, 115, 122, 131, 115, 107, 99, 125, 111]

In [10]:
## средняя и дисперсия
print ('средняя M(a) =', np.mean(iq))
print ('стандарное отклонение =', np.std(iq, ddof=1))

средняя M(a) = 118.1
стандарное отклонение = 10.54566788359614


In [11]:
# доверительный интервал
print(118.1-(2.262*np.std(iq, ddof=1)/sqrt(len(iq))))
print(118.1+(2.262*np.std(iq, ddof=1)/sqrt(len(iq))))

110.55660776308164
125.64339223691834


Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

Формула нахождения довертельного интервала:

$$ \overline x \pm (Z_{a/2} \cdot \frac{\sigma}{\sqrt{n}})$$

Дисперсия = 25 кв. см. Зачит среднеквадратичное отклонение $ \sigma = \sqrt {25}=5$

α=5% . т.к. у нас не односторонний критерий, то для вычеслений используем 2.5%.
При α=0.025 $z$ табличное = 1.96. Найдем интервал:
$$ 174.2 \pm (1.96 \cdot \frac{5}{\sqrt{27}})$$

т.е. доверительный интервал лежит в диапазоне $[172.31; 176.09]$ с 5% вероятностью ошибки


In [12]:
# доверительный интервал
print(174.2-(1.96*5/sqrt(27)))
print(174.2+(1.96*5/sqrt(27)))

172.31398912064722
176.08601087935276
