Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np
import seaborn as sns
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
X=zp
y=ks

In [2]:
X=X.reshape(10,1)
X1=X # сделаем копию X для расчета без X1= intercept

In [3]:
y=y.reshape(10,1)
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [4]:
X=np.hstack([np.ones((10,1)),X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [5]:
# Для уровнения вида y=b1+b2x (т.е. с intercept)
B=np.dot(np.linalg.inv(np.dot(X.T,X)),X. T@y)
B

array([[444.17735732],
       [  2.62053888]])

In [6]:
# Для уровнения вида y=b1x (т.е. БЕЗ intercept)
B=np.dot(np.linalg.inv(np.dot(X1.T,X1)),X1. T@y)
B

array([[5.88982042]])

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [7]:
# y=b1x
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
X=zp
y=ks

In [8]:
def mse_(B1,y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

In [9]:
alpha= 1e-6
B1=0.1
n=10
alpha

1e-06

In [10]:
for i in range(1000):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%100==0:
        print (f'Iteration: {i}, B1={B1}, mse={mse_(B1)}')

Iteration: 0, B1=0.25952808, mse=493237.7212546963
Iteration: 100, B1=5.54537842245223, mse=58151.31823171113
Iteration: 200, B1=5.868748638669329, mse=56522.97550129376
Iteration: 300, B1=5.888531320728348, mse=56516.88130936019
Iteration: 400, B1=5.8897415574471985, mse=56516.85850140053
Iteration: 500, B1=5.889815595583751, mse=56516.858416040064
Iteration: 600, B1=5.889820124983314, mse=56516.85841572062
Iteration: 700, B1=5.889820402076462, mse=56516.85841571941
Iteration: 800, B1=5.88982041902807, mse=56516.8584157194
Iteration: 900, B1=5.889820420065112, mse=56516.85841571941


In [ ]:
Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (c intercept).

In [15]:
# y=b1+b2x
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
X=zp
y=ks

alpha= 0.00007
B1=100
B2=100
n=10
alpha

7e-05

In [17]:
for i in range(150000):
    
    # Считаем результат используя найденные коф-ты B1,B2
    y_temp = B1 + B2*X  
    
    # считаем отклонение нового результата от истенного:
    error = (y - y_temp)
    
    # считаем градиенты: 
    B1_grad = -2 * error.mean()
    B2_grad = -2 * (X * error).mean()
    
    # обновляем параметры
    B1 = B1 - alpha * B1_grad
    B2 = B2 - alpha * B2_grad
print(B1,B2)  

444.12927137482205 2.6208928162513816


В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

#### При известной дисперсии используют таблицу значений функции Лапласа, а  при неизвестной дисперсии - таблицу критических точек распределения Стьюдента